[plugin]
repository = "https://github.com/Styr1x/Browsingway.git"
commit = "c0b4b9d7076382b1a9ac804ef2a22a622a1a810e"
owners = ["Styr1x"]
project_path = "Browsingway"
changelog = """\
- Bump Chromium to 134.0.6998.118
- Api 12 support
"""
