[plugin]
repository = "https://github.com/Styr1x/Browsingway.git"
commit = "5b6c7af16cad9ecd849dfb9e349fc18cb2a2460c"
owners = ["Styr1x"]
project_path = "Browsingway"
changelog = """\
- Add IINACT (Dalamud Plugin) support
- Fix Dalamud UI corruption because of unhandled exception
"""
